http:
  enabled: true
  address: 0.0.0.0:4195
  root_path: /
  debug_endpoints: false

input:
  generate:
    count: 100000000
    interval: ""
    mapping: |
      this = root
      root.answer = counter()
      root.contract = if root.answer % 2 == 0 {
         "a"
      } else {
        "b"
      }

pipeline:
  threads: -1
  processors:
    - label: "sleep"
      sleep:
        duration: "5s"
    - label: "log_line"
      log:
        level: INFO
        fields_mapping: ""
        message: "${! this }"
    - label: "filter"
      bloblang: |
        root = if this.answer < 10 {
          deleted()
        }
    - label: mock_benthos_gauge_metric
      metric:
        type: gauge
        name: mock_benthos_gauge
        labels:  
          contract: "${! this.contract }"
        value: "${! this.answer }"
    - label: mock_benthos_gauge_metric_no_label
      metric:
        type: gauge
        name: mock_benthos_gauge_no_label
        value: "${! this.answer }"
    - label: mock_benthos_counter_metric
      metric:
        type: counter
        name: mock_benthos_counter
        labels:  
          contract: "${! this.contract }"
output:
  label: "noop"
  drop: {}

logger:
  level: ${LOG_LEVEL:INFO}
  format: logfmt
  add_timestamp: true
  timestamp_name: time
  message_name: msg
  static_fields:
    '@service': test-benthos-pipeline