global:
  scrape_interval:     1s

scrape_configs:
  - job_name:       'test'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:2112', 'host.docker.internal:4195']
        labels:
          group: 'go-client'